### PR TITLE
Add the blog1 of Ya Xiao

### PR DESCRIPTION
**Pull request by GraceXiaoYa**

### CODE REVIEW

**Comment by n1ngz** [comment]
hmm, why is there two level of the same name ?

**Comment by n1ngz** [comment]
Ya, the format doesn't seem to match, please verify your website template

**Comment by GraceXiaoYa** [comment]
Hi Dr. Zhang,

I have deployed it in a GitHub page(https://yaxiao-ariel.github.io) to see
the effect. It seems to be able to show normally. Could you tell me what's
wrong with the format?

Yours sincerely,
Ya

2017-10-13 20:42 GMT-04:00 N1ng Zh@ng <notifications@github.com>:

**Comment by n1ngz** [comment]
I think the problem lies in the fact that the class web page does not have
the CSS and javascript in as in your personal deployment.

**Pull request merged**
